### ISSUE TITLE
Drive any parameter

### ISSUE THREAD

**Issue by Augustronic** [ryanontheinside/ComfyUI_RyanOnTheInside#22]
Is there a hack to drive any parameter, for example for AdvancedLivePortrait?

**Comment by ryanontheinside** [comment]
Its funny you should ask that. There is no hack to make anything work, but I have already completed the work for AdvancedLivePortrait. I have a fully reactive version locked and loaded, I am just waiting got hear back from the author of the original repo. It's been a bit already since i reached out, so I will probably just release the modified version if I don't hear back soon.
